### ISSUE TITLE
Callback never fired if read stream emits an error

### ISSUE THREAD

**Issue by olalonde** [maxogden/concat-stream#50]
I noticed that the callback is never fired if for example a readable stream that pipes to it emits an error. This is somewhat unexpected behaviour and I'm not sure if it's by design or a bug.

e.g.:

```javascript
const concat = require('concat-stream')
const MeterStream = require('meterstream')

const arrToReadStream = (arr) => (
  new Readable({
    read() {
      const buf = arr.shift()
      process.nextTick(() => {
        if (typeof buf === 'undefined') {
          return this.push(null)
        }
        this.push(buf)
      })
    },
  })
)

const rs = arrToReadStream([Buffer.alloc(10, 'a'), Buffer.alloc(90, 'b'), Buffer.alloc(1, 'c')])
rs.pipe(new MeterStream(100))
  .on('error', (err) => {
    t.ok(err instanceof MeterStream.OverflowError)
  })
  // never fired....
  .pipe(concat(console.log))
```

This is somewhat unexpected because if you pipe to `process.stdout` or listen for `.on('data')` events, some data is piped before the error is fired. Also, from what I understand, Node.js streams that are being piped to don't typically have a way to know whether an error happened upstream.

**Comment by maxogden** [comment]
it's by design, the recommended way to handle errors is here: https://github.com/maxogden/concat-stream#error-handling

**Comment by olalonde** [comment]
Ah, for some reason I was under the impression that readable stream called `.end` on the writable streams they piped to when they emitted an error.
