### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by livey0u** [maxogden/concat-stream#55]
Hi,

I found this vulnerability(uninit mem) https://snyk.io/vuln/npm:concat-stream:20160901.
This fork seems to have fixed it. https://github.com/substack/node-concat-stream.
Should they(substack) have to make a pull request? Or can it be merged by another fork of substack?

Thanks

**Comment by KenanY** [comment]
That report page indicates that the vulnerability was fixed by https://github.com/maxogden/concat-stream/pull/47.

**Comment by mafintosh** [comment]
Yep.
