### ISSUE TITLE
Buffer Overhead Vulnerability

### ISSUE THREAD

**Issue by justingreenberg** [maxogden/concat-stream#56]
Node Security Project has [released a Buffer Overhead Vulnerability advisory](https://nodesecurity.io/advisories/142)  for this project, please see: https://nodesecurity.io/advisories/142 ([CVSS high priority](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N)) dependency

>### Overview
>concat-stream is a writable stream that concatenates all the data from a stream and calls a callback with the result. By supplying a numeric value to the write function, in certain circumstances it is possible to cause a buffer overread which will read arbitrary memory.
>### Remediation
>Consider using the --zero-fill-buffers command line argument to zero out buffer before using them. Avoid passing numeric values to the write function.
>### References
>https://nodejs.org/api/buffer.html#buffer_the_zero_fill_buffers_command_line_option

**Comment by rmg** [comment]
I don't think this is valid. This specific case appears to have been addressed almost a year ago in 3e285ba5e5b10b7c98552217f5c1023829efe69e.

**Comment by justingreenberg** [comment]
@rmg 👍 3e285ba5e5b10b7c98552217f5c1023829efe69e should have corrected this issue

either way very bizarre, likely a bug in NSP since they have already pulled down the advisory
